[package]
name = "indracore-archive"
version = "0.2.1"
authors = ["Andrew Plaza <aplaza@liquidthink.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
substrate-archive = { path = "../substrate-archive", features = ["logging"] }
substrate-archive-common = { path = "../substrate-archive-common" }
substrate-archive-backend = { path = "../substrate-archive-backend" }
node-indracore-runtime = { git = "https://github.com/selendra/indracore", default-features = false, branch = "main" }
node-cli = { git = "https://github.com/selendra/indracore", branch = "main" }
node-executor = { git = "https://github.com/selendra/indracore", branch = "main" }

clap = { version = "2.33.1", features = ["yaml", "suggestions", "color"] }
toml = "0.5"
futures = "0.3.5"
log = "0.4"
pretty_env_logger = "0.4.0"
anyhow = "1.0.31"
serde = "1.0"
ctrlc = { version = "3.1.5", features = ["termination"] }

[features]
